# Generated by Django 3.0.3 on 2020-08-15 00:28

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('camera_make', models.CharField(max_length=50)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('key', models.CharField(max_length=100)),
                ('pano', models.BooleanField(default=False)),
                ('user_key', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('geometry_coordinates', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
