# Generated by Django 3.0.3 on 2020-09-28 19:00

import colorful.fields
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sequence.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('font_awesome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cas', models.FloatField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('seq_key', models.CharField(default='', max_length=100)),
                ('image_key', models.CharField(max_length=100)),
                ('pano', models.BooleanField(default=False)),
                ('user_key', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('organization_key', models.CharField(max_length=255, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_privated', models.BooleanField(default=False)),
                ('is_mapillary', models.BooleanField(default=True)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('ele', models.FloatField(default=0)),
                ('type', models.CharField(default='Point', max_length=50)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('mapillary_image', models.ImageField(blank=True, null=True, upload_to=sequence.models.image_directory_path)),
                ('camera_make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.CameraMake')),
                ('camera_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.CameraModel')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('seq_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary Sequence Key')),
                ('pano', models.BooleanField(default=False)),
                ('user_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary User Key')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary Username')),
                ('geometry_coordinates', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('geometry_coordinates_ary', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1), size=None), blank=True, null=True, size=None)),
                ('coordinates_cas', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, null=True, size=None)),
                ('coordinates_image', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_privated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image_count', models.IntegerField(default=0)),
                ('is_mapillary', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('google_street_view', models.BooleanField(default=False)),
                ('strava', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('camera_make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.CameraMake')),
                ('tag', models.ManyToManyField(to='sys_setting.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TransType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.Icon')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sequence.TransType')),
            ],
            options={
                'verbose_name_plural': 'Transport Type',
            },
        ),
        migrations.CreateModel(
            name='SequenceLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='transport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.TransType'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LabelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('polygon', 'polygon')], default='polygon', max_length=50)),
                ('color', colorful.fields.RGBColorField(default='#ffffff')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sequence.LabelType')),
            ],
            options={
                'verbose_name_plural': 'Image Label Type',
            },
        ),
        migrations.CreateModel(
            name='ImageViewPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Image')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Image')),
                ('label_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.LabelType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_label',
            field=models.ManyToManyField(through='sequence.ImageLabel', to='sequence.LabelType'),
        ),
        migrations.AddField(
            model_name='image',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
