# Generated by Django 3.0.3 on 2020-09-29 11:27

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltype',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
