# Generated by Django 3.0.3 on 2020-08-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='key',
            new_name='seq_key',
        ),
    ]
