# Generated by Django 3.0.3 on 2020-08-20 11:34

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='0', max_length=6), null=True, size=None)),
                ('name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='key',
            new_name='seq_key',
        ),
        migrations.AddField(
            model_name='sequence',
            name='coordinates_cas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sequence',
            name='coordinates_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sequence',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sequence',
            name='geometry_coordinates_ary',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_mapillary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_privated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sequence',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='0', max_length=6), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='camera_make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='captured_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='geometry_coordinates',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='TourSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='transport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.TransportType'),
        ),
    ]
