# Generated by Django 3.0.3 on 2020-08-16 18:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_auto_20200815_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='coordinates_cas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sequence',
            name='coordinates_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_privated',
            field=models.BooleanField(default=False),
        ),
    ]
