# Generated by Django 3.0.3 on 2020-08-28 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequence', '0002_auto_20200824_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('camera_make', models.CharField(default='', max_length=150)),
                ('camera_model', models.CharField(default='', max_length=150)),
                ('cas', models.FloatField(default=0)),
                ('captured_at', models.DateTimeField(null=True)),
                ('seq_key', models.CharField(default='', max_length=100)),
                ('image_key', models.CharField(max_length=100)),
                ('pano', models.BooleanField(default=False)),
                ('user_key', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('organization_key', models.CharField(max_length=255, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_privated', models.BooleanField(default=False)),
                ('is_mapillary', models.BooleanField(default=True)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('type', models.CharField(default='Point', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
