# Generated by Django 3.0.3 on 2020-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_auto_20200929_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltype',
            name='source',
            field=models.CharField(choices=[('mtpw', 'MTPW'), ('mapillary', 'Mapillary')], default='mtpw', max_length=50),
        ),
    ]
