# Generated by Django 3.0.3 on 2020-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0003_labeltype_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
