# Generated by Django 3.0.3 on 2020-08-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourlike',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toursequence',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='toursequence',
            name='tour',
        ),
        migrations.DeleteModel(
            name='TourTag',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourLike',
        ),
        migrations.DeleteModel(
            name='TourSequence',
        ),
    ]
