# Generated by Django 3.0.3 on 2020-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0004_auto_20200828_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttype',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
