# Generated by Django 3.0.3 on 2020-08-16 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0004_auto_20200816_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='geometry_coordinates_ary',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1), size=None), null=True, size=None),
        ),
    ]
