# Generated by Django 3.0.3 on 2020-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0006_auto_20200817_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='is_mapillary',
            field=models.BooleanField(default=True),
        ),
    ]
