# Generated by Django 3.0.3 on 2020-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0007_auto_20201011_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_privated',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='is_privated',
            new_name='is_private',
        ),
    ]
