# Generated by Django 3.0.3 on 2020-08-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0008_sequence_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='transport_type',
        ),
    ]
