# Generated by Django 3.0.3 on 2020-10-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0009_mapfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeatureDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(blank=True, max_length=100, null=True)),
                ('detection_key', models.CharField(blank=True, max_length=100, null=True)),
                ('user_key', models.CharField(blank=True, max_length=100, null=True)),
                ('mf_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapfeature',
            name='detections',
        ),
    ]
