# Generated by Django 3.0.3 on 2020-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0009_auto_20200829_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transtype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
