# Generated by Django 3.0.3 on 2020-10-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0010_auto_20201019_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapFeatureDetection',
        ),
    ]
