# Generated by Django 3.0.3 on 2020-08-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0010_auto_20200829_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportType',
        ),
    ]
