# Generated by Django 3.0.3 on 2020-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0011_delete_transporttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transtype',
            options={'verbose_name_plural': 'Transport Type'},
        ),
        migrations.AddField(
            model_name='sequence',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
