# Generated by Django 3.0.3 on 2020-10-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0012_mapfeaturedetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfeaturedetection',
            name='map_feature',
        ),
        migrations.DeleteModel(
            name='MapFeature',
        ),
        migrations.DeleteModel(
            name='MapFeatureDetection',
        ),
    ]
