# Generated by Django 3.0.3 on 2020-08-30 18:13

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0013_imageviewpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filename', models.ImageField(null=True, upload_to=sequence.models.icon_image_directory_path)),
            ],
        ),
    ]
