# Generated by Django 3.0.3 on 2020-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0014_tour_toursequence_tourtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toursequence',
            name='sort',
            field=models.IntegerField(default=1),
        ),
    ]
