# Generated by Django 3.1.2 on 2020-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0015_auto_20201020_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='is_image_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='is_map_feature',
            field=models.BooleanField(default=False),
        ),
    ]
