# Generated by Django 3.0.3 on 2020-08-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0018_auto_20200831_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='is_transport',
        ),
    ]
