# Generated by Django 3.0.3 on 2020-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0018_image_map_feature_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
