# Generated by Django 3.0.3 on 2020-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0019_remove_sequence_is_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='font_awesome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
