# Generated by Django 3.0.3 on 2020-10-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0020_tmpsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='TmpSequence',
        ),
    ]
