# Generated by Django 3.0.3 on 2020-09-01 07:32

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0020_auto_20200901_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to=sequence.models.icon_image_directory_path),
        ),
    ]
