# Generated by Django 3.0.3 on 2020-11-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0022_sequence_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='updated_at',
            new_name='imported_at',
        ),
    ]
