# Generated by Django 3.0.3 on 2020-12-05 16:17

from django.db import migrations, models
import sequence.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0023_auto_20201125_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='static_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=''), upload_to=sequence.models.sequence_image_directory_path),
        ),
    ]
