# Generated by Django 3.0.3 on 2020-12-05 21:06

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0024_sequence_static_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='static_image',
            field=models.ImageField(blank=True, null=True, upload_to=sequence.models.sequence_image_directory_path),
        ),
    ]
