# Generated by Django 3.0.3 on 2020-12-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0025_auto_20201205_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='static_image',
        ),
    ]
