# Generated by Django 3.0.3 on 2020-09-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0025_remove_icon_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence'),
        ),
    ]
