# Generated by Django 3.0.3 on 2020-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0027_auto_20201215_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='google_street_view',
            field=models.TextField(blank=True, default=''),
        ),
    ]
