# Generated by Django 3.0.3 on 2020-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0027_auto_20200914_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ele',
            field=models.FloatField(default=0),
        ),
    ]
