# Generated by Django 3.0.3 on 2020-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0028_auto_20201217_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_point_count',
            field=models.IntegerField(default=0),
        ),
    ]
