# Generated by Django 3.0.3 on 2020-09-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0028_image_ele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ele',
        ),
    ]
