# Generated by Django 3.0.3 on 2020-09-16 18:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0030_image_ele'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='image',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
