# Generated by Django 3.0.3 on 2020-09-16 19:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequence', '0031_auto_20200916_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('area', models.FloatField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('image_ca', models.FloatField(default=0)),
                ('image_key', models.CharField(max_length=100)),
                ('image_pano', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('shape_type', models.CharField(max_length=50)),
                ('shape_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('shape_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('value', models.CharField(max_length=100)),
                ('geometry_type', models.CharField(max_length=50)),
                ('geometry_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.Image')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
