# Generated by Django 3.0.3 on 2020-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0032_imagedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetection',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
