# Generated by Django 3.0.3 on 2020-09-16 20:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0034_imagedetection_det_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetection',
            name='shape_polygon',
        ),
        migrations.AddField(
            model_name='imagedetection',
            name='shape_multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
