# Generated by Django 3.0.3 on 2020-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0036_mapfeature_mapfeaturedetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary Sequence Key'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='user_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary User Key'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mapillary Username'),
        ),
    ]
