# Generated by Django 3.0.3 on 2020-09-18 19:04

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0037_auto_20200918_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mapillary_image',
            field=models.ImageField(blank=True, null=True, upload_to=sequence.models.image_directory_path),
        ),
    ]
