# Generated by Django 3.0.3 on 2020-09-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0038_image_mapillary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagedetection',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='imagedetection',
            name='user',
        ),
    ]
