# Generated by Django 3.0.3 on 2020-09-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0039_auto_20200919_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
