# Generated by Django 3.0.3 on 2020-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0040_cameramake'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='google_street_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequence',
            name='strava',
            field=models.BooleanField(default=False),
        ),
    ]
