# Generated by Django 3.0.3 on 2020-09-24 17:59

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0041_auto_20200923_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sequence.LabelType')),
            ],
            options={
                'verbose_name_plural': 'Image Label Type',
            },
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Image')),
                ('label_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.LabelType')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_label',
            field=models.ManyToManyField(through='sequence.ImageLabel', to='sequence.LabelType'),
        ),
    ]
