# Generated by Django 3.0.3 on 2020-09-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0043_labeltype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_label',
        ),
        migrations.DeleteModel(
            name='ImageLabel',
        ),
    ]
