# Generated by Django 3.0.3 on 2020-09-24 18:12

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequence', '0044_auto_20200924_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Image')),
                ('label_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.LabelType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_label',
            field=models.ManyToManyField(through='sequence.ImageLabel', to='sequence.LabelType'),
        ),
    ]
