# Generated by Django 3.0.3 on 2020-09-24 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0045_auto_20200924_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
