# Generated by Django 3.0.3 on 2020-09-25 08:20

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0047_auto_20200925_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltype',
            name='color',
            field=colorful.fields.RGBColorField(default='#ffffff'),
        ),
    ]
