# Generated by Django 3.0.3 on 2020-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0049_cameramodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='camera_make',
        ),
        migrations.AddField(
            model_name='image',
            name='camera_make',
            field=models.ManyToManyField(to='sequence.CameraMake'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='camera_model',
        ),
        migrations.AddField(
            model_name='image',
            name='camera_model',
            field=models.ManyToManyField(to='sequence.CameraModel'),
        ),
    ]
