# Generated by Django 3.0.3 on 2020-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0052_auto_20200925_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='strava',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
