# Generated by Django 3.0.3 on 2020-09-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0053_auto_20200926_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapFeatureDetection',
        ),
    ]
