# Generated by Django 3.0.3 on 2020-09-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0054_delete_mapfeaturedetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageDetection',
        ),
        migrations.DeleteModel(
            name='MapFeature',
        ),
    ]
