# Generated by Django 3.0.3 on 2020-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0056_imageviewpoint_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
