# Generated by Django 3.0.3 on 2020-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0031_auto_20200928_0916'),
        ('tour', '0009_auto_20200928_0916'),
        ('sys_setting', '0001_initial'),
        ('sequence', '0058_auto_20200927_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='tag',
            field=models.ManyToManyField(to='sys_setting.Tag'),
        ),
    ]
