# Generated by Django 3.0.3 on 2020-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
