# Generated by Django 3.0.3 on 2020-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tag',
        ),
        migrations.AddField(
            model_name='tour',
            name='tag',
            field=models.ManyToManyField(to='tour.TourTag'),
        ),
    ]
