# Generated by Django 3.0.3 on 2020-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20200831_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
