# Generated by Django 3.0.3 on 2020-09-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20200901_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed for Username.')]),
        ),
    ]
