# Generated by Django 3.0.3 on 2020-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0055_auto_20200926_1427'),
        ('tour', '0007_auto_20200901_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourTag',
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_tag',
            field=models.ManyToManyField(to='sequence.Tag'),
        ),
    ]
