# Generated by Django 3.0.3 on 2020-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_setting', '0001_initial'),
        ('tour', '0008_auto_20200926_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_tag',
            field=models.ManyToManyField(to='sys_setting.Tag'),
        ),
    ]
