# Generated by Django 3.0.3 on 2020-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0003_auto_20200730_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
