# Generated by Django 3.0.3 on 2020-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0006_auto_20200730_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
    ]
