# Generated by Django 3.0.3 on 2020-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0010_remove_pointofinterest_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
