# Generated by Django 3.0.3 on 2020-08-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0018_auto_20200811_0321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SceneCategory',
            new_name='POICategory',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='category',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guidebook.POICategory'),
        ),
    ]
