# Generated by Django 3.0.3 on 2020-08-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0019_auto_20200811_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poicategory',
            options={'verbose_name_plural': 'POI Categories'},
        ),
    ]
