# Generated by Django 3.0.3 on 2020-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='image_quality',
        ),
        migrations.AddField(
            model_name='photographer',
            name='image_quality',
            field=models.ManyToManyField(to='photographer.ImageQuality'),
        ),
    ]
