# Generated by Django 3.0.3 on 2020-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_photographer_multipolygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
