# Generated by Django 3.0.3 on 2020-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0003_auto_20200908_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='capture_method',
        ),
        migrations.AddField(
            model_name='photographer',
            name='capture_method',
            field=models.ManyToManyField(to='photographer.CaptureMethod'),
        ),
    ]
