# Generated by Django 3.0.3 on 2020-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_auto_20200917_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='type',
        ),
        migrations.AddField(
            model_name='photographer',
            name='capture_type',
            field=models.ManyToManyField(to='photographer.CaptureType'),
        ),
    ]
