# Generated by Django 3.0.3 on 2020-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_auto_20200917_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagequality',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
