# Generated by Django 3.0.3 on 2020-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_setting', '0004_businesstier_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence_limit_count', models.IntegerField(default=5)),
            ],
        ),
    ]
