# Generated by Django 3.0.3 on 2020-11-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_setting', '0005_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
