# Generated by Django 3.0.3 on 2020-12-24 12:26

from django.db import migrations, models
import storages.backends.s3boto3
import sys_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_setting', '0007_auto_20201208_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstier',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='staging-backpack.mtp.trekview.org'), upload_to=sys_setting.models.image_directory_path),
        ),
    ]
