# Generated by Django 3.0.3 on 2020-07-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='organ_category',
            new_name='organisation_category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='organ_name',
            new_name='organisation_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='organ_website',
            new_name='organisation_website',
        ),
    ]
