# Generated by Django 3.0.3 on 2020-07-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200720_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_paid',
        ),
    ]
