# Generated by Django 3.0.3 on 2020-07-21 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_remove_worker_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerEnquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='JobApply',
            new_name='JobApplication',
        ),
        migrations.RenameModel(
            old_name='Worker',
            new_name='Photographer',
        ),
        migrations.DeleteModel(
            name='WorkerHire',
        ),
        migrations.AddField(
            model_name='photographerenquire',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Photographer'),
        ),
        migrations.AddField(
            model_name='photographerenquire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
