# Generated by Django 3.0.3 on 2020-07-21 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20200721_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='capture_method',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='capture_method',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='capture_method',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photographer',
            name='capture_method',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photographer',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
