# Generated by Django 3.0.3 on 2020-07-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20200721_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(),
        ),
    ]
