# Generated by Django 3.0.3 on 2020-07-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20200721_2023'),
        ('marketplace', '0006_auto_20200721_2222'),
    ]

    operations = [
    ]
