# Generated by Django 3.0.3 on 2020-07-22 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20200722_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='capture_method',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='type',
        ),
        migrations.AddField(
            model_name='photographer',
            name='capture_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='1', max_length=3), null=True, size=None),
        ),
        migrations.AddField(
            model_name='photographer',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='1', max_length=3), null=True, size=None),
        ),
    ]
