# Generated by Django 3.0.3 on 2020-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_job_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
