# Generated by Django 3.0.3 on 2020-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20200727_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
