# Generated by Django 3.0.3 on 2020-07-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_capturemethod_capturetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptureMethod',
        ),
        migrations.DeleteModel(
            name='CaptureType',
        ),
    ]
