# Generated by Django 3.0.3 on 2020-07-27 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20200727_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quality',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='photographer',
            name='quality',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='capture_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='0', max_length=3), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='0', max_length=3), null=True, size=None),
        ),
    ]
