# Generated by Django 3.0.3 on 2020-07-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_capturemethod_capturetype_organisationcategory_quality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quality',
            new_name='ImageQuality',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='quality',
            new_name='image_quality',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='quality',
            new_name='image_quality',
        ),
    ]
