# Generated by Django 3.0.3 on 2020-08-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20200729_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_paid',
        ),
    ]
