# Generated by Django 3.0.3 on 2020-12-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201201_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Grade'),
        ),
        migrations.DeleteModel(
            name='UserGrade',
        ),
    ]
