# Generated by Django 3.0.3 on 2020-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_custombanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombanner',
            name='linked_url',
            field=models.TextField(null=True),
        ),
    ]
