# Generated by Django 3.0.3 on 2020-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201208_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=255),
        ),
    ]
