# Generated by Django 3.0.3 on 2020-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grade_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='hall_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='hall_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
