# Generated by Django 3.0.3 on 2020-07-22 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200722_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_confirm_text',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed for Username.')]),
        ),
    ]
