# Generated by Django 3.0.3 on 2020-07-22 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200722_1617'),
    ]

    operations = [
        
    ]
