# Generated by Django 3.0.3 on 2020-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201208_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='hall_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
