# Generated by Django 3.0.3 on 2020-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_email_confirm_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
