# Generated by Django 3.0.3 on 2020-07-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200722_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_confirm_text',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_confirmed',
        ),
    ]
