# Generated by Django 3.0.3 on 2020-09-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
