# Generated by Django 3.0.3 on 2020-12-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0029_image_view_point_count'),
        ('challenge', '0002_labelchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='transport_type',
        ),
        migrations.AddField(
            model_name='challenge',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.TransType'),
        ),
    ]
