# Generated by Django 3.0.3 on 2020-09-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challenge_camera_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='expected_count',
        ),
    ]
