# Generated by Django 3.0.3 on 2020-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mapillary Username'),
        ),
    ]
