# Generated by Django 3.0.3 on 2020-10-16 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0002_scene_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
