# Generated by Django 3.0.3 on 2020-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0002_auto_20200729_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag',
            field=models.ManyToManyField(related_name='tab_name', to='guidebook.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
