# Generated by Django 3.0.3 on 2020-10-16 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0004_scene_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
