# Generated by Django 3.0.3 on 2020-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0004_auto_20200730_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='guidebook',
            name='category',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='category',
            field=models.ManyToManyField(related_name='category_name', to='guidebook.Category'),
        ),
    ]
