# Generated by Django 3.0.3 on 2020-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0005_auto_20201016_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
