# Generated by Django 3.0.3 on 2020-12-02 12:01

from django.db import migrations, models
import guidebook.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0006_guidebook_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=''), upload_to=guidebook.models.poi_image_directory_path),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='video_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=''), upload_to=guidebook.models.scene_image_directory_path),
        ),
        migrations.AddField(
            model_name='scene',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
