# Generated by Django 3.0.3 on 2020-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0007_auto_20201202_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='other_url',
            field=models.TextField(default=''),
        ),
    ]
