# Generated by Django 3.0.3 on 2020-12-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0008_pointofinterest_other_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='other_url',
            new_name='external_url',
        ),
    ]
