# Generated by Django 3.0.3 on 2020-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0009_auto_20201203_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='external_url',
        ),
        migrations.CreateModel(
            name='POIExternalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.TextField(default='')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidebook.PointOfInterest')),
            ],
        ),
    ]
