# Generated by Django 3.0.3 on 2020-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0011_auto_20201218_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneExternalURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.TextField(default='')),
            ],
            options={
                'ordering': ['external_url'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='external_url',
            field=models.ManyToManyField(to='guidebook.SceneExternalURL'),
        ),
    ]
