# Generated by Django 3.0.3 on 2020-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0012_auto_20201222_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='external_url',
            field=models.ManyToManyField(blank=True, to='guidebook.SceneExternalURL'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
