# Generated by Django 3.0.3 on 2020-08-04 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0013_auto_20200804_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='0', max_length=30), null=True, size=None),
        ),
    ]
