# Generated by Django 3.0.3 on 2020-08-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0015_scene_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scene Categories',
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guidebook.SceneCategory'),
        ),
    ]
