# Generated by Django 3.0.3 on 2020-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0016_auto_20200806_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
