# Generated by Django 3.0.3 on 2020-08-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0021_auto_20200817_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag',
            field=models.ManyToManyField(to='guidebook.Tag'),
        ),
    ]
