# Generated by Django 3.0.3 on 2020-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0055_auto_20200926_1427'),
        ('guidebook', '0028_auto_20200921_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='tag',
            field=models.ManyToManyField(to='sequence.Tag'),
        ),
    ]
